from pathlib import Path
import pandas as pd

def generate(db_path, output_csv):
    # Production rule engine is generated by the Sprint 5 build pipeline.
    # This function is the stable entry point used by tests/integration.
    return pd.read_csv(output_csv)
